spring:
  application:
    name: ms-customer
  config:
    import: ${SPRING_CONFIG_IMPORT:}
  cloud:
    config:
      enabled: ${SPRING_CLOUD_CONFIG_ENABLED:true}
  data:
    mongodb:
      auto-index-creation: true
  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}
    password: ${SPRING_REDIS_PASSWORD:}
    timeout: 60s
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://service-eureka:8761/eureka/}
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,circuitbreakers,circuitbreaker-events,retries,retry-events,rate-limiters,rate-limiter-events,time-limiters,time-limiter-events
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

cache:
  redis:
    ttl-minutes: 10
