spring:
  config:
    import: ""
  cloud:
    discovery:
      enabled: false
    config:
      enabled: false
  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST}
      port: ${SPRING_DATA_MONGODB_PORT}
      database: ${SPRING_DATA_MONGODB_DATABASE}
      authentication-database: admin
      username: ${SPRING_DATA_MONGODB_USERNAME}
      password: ${SPRING_DATA_MONGODB_PASSWORD}
  redis:
    host: redis
    port: 6379
    password: ""
eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    url: /v3/api-docs
  api-docs:
    path: /v3/api-docs
  show-actuator: false
  swagger-ui.operations-sorter: method
  swagger-ui.tagsSorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: "*"